version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  fluentd:
    image: fluentd
    container_name: fluentd
    build: 
      context: ./Fluentd

    volumes:
      - ./Fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    environment:
      - LOG_PROCESS_SCHEMA
      - LOG_PROCESS_HOST_PORT
      - LOG_PROCESS_URL
      
    depends_on:
      - elasticsearch
      
  
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    #hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    #volumes:
    #  - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_DEFAULT_EMAIL
    depends_on: 
      - postgres
    
volumes:
  elasticsearch-data:
  db-data:
  pgadmin-data:

networks:
  default:
    external:
      name: thesis_network
